<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="css/style.css">
	<link rel="stylesheet" href="libs/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="css/media.css">
</head>
<body>
	<div class="container">
	 	<div class="flex_row">
				<div class="delete-block delete-block_1">
					<img src="images/1.jpg" width="200px" height="200px" class=" image" id="showImg_1" alt="">
					<span class="close_img">&times;</span>
				</div>
				<div class="delete-block">
					<img src="images/2.jpg"  width="200px" height="200px" class=" image" id="showImg_2" alt="">
					<span class="close_img">&times;</span>
				</div>
				<div class="delete-block">
					<img src="images/3.jpg"  width="200px" height="200px" class="image" id="showImg_3" alt="">
					<span class="close_img">&times;</span>
				</div>
				<div class="delete-block">
					<img src="images/4.jpg" width="200px" height="200px" class=" image" id="showImg_4"  alt="">
					<span class="close_img">&times;</span>
				</div>
			
		</div>
		
		<div class="flex_row">
			<div class="delete-block delete-block_1">
				<img src="images/5.jpg" width="200px" height="200px" class="image" id="showImg_5"  alt="">
				<span class="close_img">&times;</span>
			</div>
			<div class="delete-block">
				<img src="images/6.jpg" width="200px" height="200px" class="image" id="showImg_6"  alt="">
				<span class="close_img">&times;</span>
			</div>
			<div class="delete-block">
				<img src="images/7.jpg" width="200px" height="200px" class="image" id="showImg_7"  alt="">
				<span class="close_img">&times;</span>
			</div>
			<div class="delete-block">
				<img src="images/8.jpg" width="200px" height="200px" class="image" id="showImg_8"  alt="">
				<span class="close_img">&times;</span>
			</div>
			
		</div>

		<div class="flex_row">
			<div class="delete-block delete-block_1">
				<img src="images/9.jpg" width="200px" height="200px" class="image" id="showImg_9"  alt="">
				<span class="close_img">&times;</span>
			</div>
			<div class="delete-block">
				<img src="images/10.jpg" width="200px" height="200px" class="image" id="showImg_10" alt="">
				<span class="close_img">&times;</span>
			</div>
			<div class="delete-block">
				<img src="images/11.jpg" width="200px" height="200px" class="image" id="showImg_11" alt="">
				<span class="close_img">&times;</span>
			</div>
			<div class="delete-block">
				<img src="images/12.jpg" width="200px" height="200px" class="image" id="showImg_12" alt="">
				<span class="close_img">&times;</span>
			</div>
			
			
		</div> 

			<div class="restore">
				<a href="#" class="button"/>RESTORE</a>
			</div>



			<div id="myModal" class="modal">
				<span class="close" onclick="document.getElementById('myModal').style.display='none'">&times;</span>
				<img class="modal-content" id="img">
				<div class="caption"></div>
			</div>
	</div>

			


	<script type="text/javascript" src="libs/jquery/jquery-1.11.2.min.js"></script>
	<script type="text/javascript" src="js/script.js"></script>
</body>
</html>
